eureka:
    client:
      enabled: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

microservice:
    payment-service:
      end-points:
        endpoint:
          uri: http://PAYMENT-SERVICE/payment/doPayment
    order-service:
      end-points:
        endpoint:
          uri: http://ORDER-SERVICE/order/bookOrder
